management.security.enabled: true

security:
  user:
    name: dodo
    password: 1qaz2wsx

spring:
  jpa:
    show-sql: true  #or properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true
  h2.console.enabled: true

logging:
  level:
    org.hibernate.type: TRACE

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 789652

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl_auto: validate

